// <auto-generated />
using System;
using Criminals.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Criminals.Data.Migrations
{
    [DbContext(typeof(CriminalsContext))]
    [Migration("20180728230312_RequiredConstraintToCaseReportsTable")]
    partial class RequiredConstraintToCaseReportsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Criminals.Data.Models.CaseReport", b =>
                {
                    b.Property<Guid>("DocketNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<DateTime>("OpenDate");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("DocketNumber");

                    b.ToTable("CaseReports");
                });
#pragma warning restore 612, 618
        }
    }
}
